### ISSUE TITLE
Excessive calls to filters.privaxy.net

### ISSUE THREAD

**Issue by ajkblue** [deetungsten/webui-privaxy#3]
Not sure if this is strictly necessary, but it seems to be making excessive calls to `filters.privaxy.net` for updates to the blocklists. From what I am seeing on my network with Pi-Hole, as well as inside the container logs, it seems to be hitting that domain once every 10 minutes times the number of blocklists enabled, which seems a little unnecessary. 

I think it would help to reduce calls to that domain to reduce the risk of possible IP bans (I assume it is the original author that is running that site?). I also can't see a reason that the ad-lists need to be updated more than once per day. Here is a snippet from the docker container logs:

```
08/26/2023 1:39:07 PM
[2023-08-26T19:39:07Z INFO  privaxy::configuration] Updated filters
08/26/2023 1:49:07 PM
[2023-08-26T19:49:07Z INFO  privaxy::configuration] Updated filters
08/26/2023 1:59:08 PM
[2023-08-26T19:59:08Z INFO  privaxy::configuration] Updated filters

```

**Comment by deetungsten** [comment]
Thank you for bringing this to my attention. This value is actually the same as the original repo. However, I just updated this fork to update the filter list once a day to reduce the bandwidth consumption on the original author's site.
